language: python
cache:
  pip: true
python:
  - '3.5'
before_install:
   - pip install coveralls
   - pip install -r requirements.txt
script:
  - coverage run -m unittest discover -s tests
after_success:
  - coveralls --verbose

