language: python
cache:
  pip: true
python:
- '3.5'
before_install:
- pip install coveralls
- pip install -r requirements.txt
script:
- python src/manage.py test dummy
- coverage run src/manage.py test dummy
- python src/manage.py test env_data
- coverage run src/manage.py test env_data
- python src/manage.py test login
- coverage run src/manage.py test login
after_success:
- coveralls --verbose
env:
  matrix:
    secure: V2oBcLUGb7JibKF71g/bot8FTQH8GXOvfpPznnbo0gbURm81QuCmIObqUTGNhjoW32jQX7dzUyBosK6UittTdZsJpjjPvPD/GtafvFVG2Xm+OCert3mUQzx58NZUXc8Yj/dPqmrfJkz53u4pcyjwyTG1Pz1wUC280aRj7n7Y9+Us+bjdoxaQ2xUKxir3SXwR1VIYlHYMibE8GiNkZVugLlnxhJ84toH0kohFMxmBZp5mhFdpB3kZj9knKDX1cWPgRpb8a28nHudRam+0AfW9HxpoXXaqbWKdz59cZoBO9evBy413+Q3cWkiWtL7COY+ezcEPCEQBHaAga/y8KrMW/RdJGaeiBILQwkHOfgWw5q6pEGXTVhyVERjHIeDtiFe9DY0i69bO0dG3BlQj3k8BLMXdq/OjxygBw0iDRBa6togrH4xFf0YN/iFeAesjVnmWmuLJZwW0YNYBKw4iDazNyDFpXAfSoEBGLMtD4IO2pQGPDcDBhPvCBUMG3yCmD3qUeTBwdUwBatS74PZQmjwFC8UKlAMW+jJ0ftjx0IEzOJ0r+GUX3/BNUkmVLwIzyY28FeD607oXokqrpeE0W0M8d2IRhICMAOgavEr5Yxs4OUuZUmK27XlU5HSKiSYMVaIwEWYmuYil5IfF5YPeQh6ZQTqaFlhW96nWQKU3B01bg3E=
