language: python
cache:
  pip: true
python:
- '3.5'
before_install:
- pip install coveralls
- pip install -r requirements.txt
before_script:
- echo '' > /tmp/plantalytics_backend.log
- printf '\n' > /tmp/plantalytics_backend.log
- cd src
script:
- python manage.py test
- coverage run manage.py test
after_script:
- rm /tmp/plantalytics_backend.log
after_success:
- coveralls --verbose
env:
  matrix:
    secure: NwbfbxGbrEkFSYupFRg7mJ0DdUVwjPvisxqCrXd9/b9I0n7DJbbGzGPna3alPNbfn2FDNdww4y+KzhNG0tABB3z3d57T6KzWXJyhnPa4P0gnlcI3qA8x3bJ2eZpqfdsB/0ndGJ8sv64xvwvLhumuxUn84z3vQ0+mM5paPpesAW/sdFHRhzVFekLPRLiKIsOgBd/mUpsvxIUYEMZQcY3XkU5YyVsIUDHg5ccBLyP8zK2aPa0i2O+9N58AXABfVC/LL2UWWQZcfINItwdtELkf/9T91ov2i/rJxLl48sHeruhDLko4kseppJtNN5KClLFvh7cIwymw4Jsp2ADcmeC0/aWg+mnUTjVIfN0EJSdq8X67yQnlmH2SWxah1cHRrdP5AIqOvE+jJPOeKZCs6gEuv7AL4/mGDwApkSZauT8zoZZr8Ii9DiNjZdUcbaarcG+iYlflr1ZwPFYNXMG/1LcfcS81C0QxoL5pgxcANFzKP0v5Rd/X+XWZvOP0tXnV/UGL3HY6QaDXNnum+E0Aoo4jLMbfFeyVQN/epmplN1y5z1mkJ2XcbDDg6wulXegToy0R09vrWlqIflBenO0M0YN5Tj4xcjuN2a5r3YkvJSc+9fAK29Hh65w+RmBe2oQIu55E9bBavfrCCR8yPFmffGk7RsruQXcKoGWSqm/K6/yf30g=
