language: python
cache:
  pip: true
python:
- '3.5'
before_install:
- pip install coveralls
- pip install -r requirements.txt
script:
- python src/manage.py test dummy
- coverage run src/manage.py test dummy
after_success:
- coveralls --verbose
env:
  matrix:
    secure: qWUCjtQ1bhEGedwf9QHwZ+eZbEzVzhVuzR+9YcjQYQL7+sk/wAxAA0hRU/OLrB1uEXXLbeq27baT+84yrFrwBF6xK1r3wFMIPepbtuTB64Efaungkn9RDFOZhUAPjw7t9I9CQPmv5WQ7r2v1sbr1ULX3Pu0sP7PIigvyt3tdZcyaaZO0SYQuanYMe35srfs2XYy1XypNaJG04fuK8gNHOOCKQU10whcp24A73bJd/7Kbgs4sIViulxcYHZPfiHvUl9VP5d7WEMccqHQuYiaC4kTQ4toDaXteI3dgnhznrz604Wcw0MwIaM68K8ThewyzaUEdmIO4ciMY0BC30rVzSlb9OggGl0+zd9GU33rw8oC329uY21hvC3oBHGypw3fJJqsSZVzyPD+vRRelllAbZzR3LnQT8zAVilpi4kY4bLww2MdRPohQEAQiDRTeiLjDXuIJDR8I37TjYvpi1Sm+qtqLp7tZslm0FipXonGbPjSq8C98wtwaDNQeJYNDo8ahhh3byZ2tNo7zZRvNb+T4s65x0Q5yGcUintDiM+wOIV9JitJDACYXE/MNZGx8On0a0BpkfwjtCWYBA5vEbq9T5LmOFDe+Lr7tYoG2nLAuNRlKKUBISKQjCVaCg1/tzzsEpyxoL4llwwfIXR/fXN1CxbGksbk4ncyQlKLNBeI2ab0=
