language: python
cache:
  pip: true
python:
- '3.5'
before_install:
- pip install coveralls
- pip install -r requirements.txt
before_script:
- echo '' > /tmp/plantalytics_backend.log
- printf '\n' > /tmp/plantalytics_backend.log
script:
- python src/manage.py test tests
- coverage run src/manage.py test tests
after_script:
- rm /tmp/plantalytics_backend.log
after_success:
- coveralls --verbose
env:
  matrix:
    secure: uAvVi24KOs/G8QHEjnrj5cJ184VwYDaU0BIjxH8wmeQhYEGDHfhmGjUzp0wakv6ewWKXPFiDI8DvkC4pHyN0UVwTiELLL61TMt9BxH9rocsfElK2gSNrvt/me8ZQM/FyMwbhgJqVgRVTMT7VLQzHZwRRefADmrHPE7UmVRXNDL/N6X+qV6m6xNf5XGpRW+RbsobHrbisaf8U2M9L9qHMZApUCIa6tA+qKqhYA5+jWI7rLLS1egrPW9VSudFiRX//lRbphMUz5Cxqu10TizmC8ISDMQVpaskNnGZ2OWmj0cbEvJFDa+DQfDTdAQfhaQdtHAqaU3toYDUmapjQLKqScvnLIWWb2F0HlqupaW512mLb2p+RC1aNAZHyj3o+umF2aHTSS93H+XNhfJLs2vlCeI6yR/Y8OAFZ4FW3MZqQmqF1NqxFIlOxraMevljDh03fPAj9XEadUW61f/i+RN4Z6VQzpDyhG0PPSg8k418Zf49CGD6Q919mPLfmA3smDX5Q7WORzbbwr3URSOtIgv1cQlV0BLCWULkUBdUzLoIWcMYA4PCfSRGKCinVRxfKMKS0Aom6T2YGQZCK5eDzRuxkZ23sC/xBWZFeD6GCRwlQz3V6mPQhX7f/0NsPo08rfJFsr6uzzP/95HFE6Osr22QrO4Z/F+b8Ny1nrORoo1y8Hb0=
