language: python
cache:
  pip: true
python:
- '3.5'
before_install:
- pip install coveralls
- pip install -r requirements.txt
script:
- python src/manage.py test dummy
- coverage run src/manage.py test dummy
after_success:
- coveralls --verbose
env:
  matrix:
    secure: CG59WvausRcrcv8LHvUgU60mmiJlSXtHBaPflyXCONfHfKtnLvoKdUnLposwG5WJN3tOJf0pUlR6NcTjxIdBemq5sHucaBRYV7hxPJT/V2qTdOnO6IGg8T5th7U2kSxzV8M3zYnZSExjT3MUCdoTzs+np89R5FvsTyo1AfFvvNtebRLpUAwQMl4o9DqaIoXETp4uZyP0Lw3c84r2Ao1tFnxeyQQipFaMJAutHnJBnKWlJh6kkcIdvd5bWimTQn3mYShPlnSmqz3kE8h2CREuam6ybGJtJ2k1uFukmuvh9jpq4m3ldQXF8bwL9QPhbS2xl0RNCEDr42kXYrxVBD3wkw6TdnVy36JM9yycl1kP7rpaZ6yXA9K8mQybrd5OgWqmOM+kOIb6nbntGjW/0pvlBLIneqdhknRWewDVY/Goxp8RM/xEjBxlWDyCrKc+waGSc35X6wQQTJ/0zjF7YBHSpARnP5tuks9mownhg3l5WywJZzNABsjuw6V99kTQPLG78aRx0tGjg0kPQqKjljMOSSsBl/KbuCHYtirZGBQ8m/NWvU1P2JJ8lFrjGR51XqK61C7KBw/E5sREy8KME45Ir9dSRHMzoe3smrhDZ2Zd6x/L0h/0lc7hEQf1R1CGmhkzS+37T3l1CjRoSqyxgNfxFph4lNUvSCGZ1qun7wpdJPo=
